# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{tripwire}
  s.version = "1.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Brendan Baldwin"]
  s.date = %q{2010-01-09}
  s.default_executable = %q{tripwire}
  s.description = %q{Similar to rstakeout and autotest except more options}
  s.email = %q{brendan@usergenic.com}
  s.executables = ["tripwire"]
  s.extra_rdoc_files = [
    "README.txt"
  ]
  s.files = [
    ".gitignore",
     "History.txt",
     "Manifest.txt",
     "README.txt",
     "Rakefile",
     "bin/tripwire",
     "lib/tripwire.rb",
     "lib/tripwire/cli.rb",
     "lib/tripwire/runner.rb",
     "lib/tripwire/scanner.rb",
     "spec/scanner_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb",
     "tripwire.gemspec"
  ]
  s.homepage = %q{http://github.com/brendan/tripwire}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Executes a shell command every time file/folder changes}
  s.test_files = [
    "spec/scanner_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
    else
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
  end
end

